title: Terrance Wells Jr.# your name (or website title) here
logo: "/images/IMG-0767.jpg?raw=true" # your photo  here
description: > # your text below (remove <br> elements if you don't need line breaks)
  As a personal trainer and a writer, both tell stories. One through physical characteristics, the other 
  develops characters mentally. As a software developer I get to tell stories with each line of code I write. 
  I created a value system for myself that I live by and it's called, "LEE" (Leadership, Ethics, Empathy). 
  I lead by example, and never compromise my ethics, and I am empathetic to the people I work with and for. 
  I am a full stack developer who specializes in HTML/CSS and JavaScript. I am experienced in working individually 
  and with a team to produce dynamic websites. 
  
  <br><br>
  <a href="http://www.linkedin.com/in/terrance-wells-jr-b57a32241">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
